# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbMember',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
                ('membercode', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=12)),
                ('birthday', models.CharField(max_length=12)),
                ('sex', models.CharField(max_length=2)),
                ('height', models.CharField(max_length=3)),
                ('weight', models.CharField(max_length=3)),
                ('activility', models.CharField(max_length=2)),
                ('insertdate', models.DateField()),
                ('updatedate', models.CharField(blank=True, max_length=50, null=True)),
                ('updateuser', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TB_MEMBER',
                'managed': False,
            },
        ),
    ]
