# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbRecord',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
                ('ptrymd', models.TextField(blank=True, max_length=12, null=True)),
                ('ptprogram', models.TextField(blank=True, null=True)),
                ('membercode', models.TextField(blank=True, null=True)),
                ('ptrcomment', models.TextField(blank=True, null=True)),
                ('ptrsessionf', models.CharField(blank=True, max_length=2, null=True)),
                ('ptrsessionl', models.CharField(blank=True, max_length=2, null=True)),
                ('ptrfrequency', models.CharField(blank=True, max_length=1, null=True)),
                ('ptrintensity', models.CharField(blank=True, max_length=3, null=True)),
                ('ptrtime', models.CharField(blank=True, max_length=3, null=True)),
                ('ptrtype', models.CharField(blank=True, max_length=12, null=True)),
                ('ptrmpcnt', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
