# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbrecord',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='tbrecord',
            table='TB_Record',
        ),
    ]
