# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_record', '0002_auto_20171202_0551'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbrecord',
            table='TB_Record',
        ),
    ]
