# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbAdminaccount',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
                ('accountid', models.CharField(max_length=24)),
                ('accountpw', models.CharField(max_length=70)),
                ('accountnm', models.CharField(max_length=10)),
                ('accountph', models.CharField(blank=True, max_length=15, null=True)),
                ('accountdpt', models.CharField(blank=True, max_length=60, null=True)),
                ('accountemail', models.CharField(blank=True, max_length=60, null=True)),
                ('accountlv', models.CharField(max_length=2)),
                ('state', models.CharField(blank=True, max_length=1, null=True)),
                ('insertuser', models.CharField(blank=True, max_length=24, null=True)),
                ('updateuser', models.CharField(blank=True, max_length=24, null=True)),
                ('updatedate', models.CharField(blank=True, max_length=21, null=True)),
                ('insertdate', models.CharField(max_length=21)),
            ],
            options={
                'db_table': 'TB_ADMINACCOUNT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membercode', models.CharField(max_length=14)),
                ('rhr', models.CharField(blank=True, max_length=2, null=True)),
                ('e_mhr', models.CharField(blank=True, max_length=3, null=True)),
                ('vo2max', models.CharField(blank=True, max_length=2, null=True)),
                ('mhr', models.CharField(blank=True, max_length=3, null=True)),
                ('recovery', models.CharField(blank=True, max_length=1, null=True)),
                ('frequency', models.CharField(max_length=2)),
                ('intensity', models.CharField(max_length=6)),
                ('target_time', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('wt', models.IntegerField()),
                ('l1', models.CharField(max_length=10)),
                ('it', models.IntegerField()),
                ('repeat', models.IntegerField()),
                ('l2', models.CharField(max_length=10)),
                ('rt', models.IntegerField()),
                ('ct', models.IntegerField()),
                ('l3', models.CharField(max_length=10)),
                ('weight', models.CharField(blank=True, max_length=3, null=True)),
                ('insertdate', models.DateField(unique=True)),
                ('speed', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TB_MEASUREMENT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbMember',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
                ('membercode', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=12)),
                ('birthday', models.CharField(max_length=12)),
                ('sex', models.CharField(max_length=2)),
                ('height', models.CharField(max_length=3)),
                ('weight', models.CharField(max_length=3)),
                ('activility', models.CharField(max_length=2)),
                ('insertdate', models.DateField()),
                ('updatedate', models.CharField(blank=True, max_length=50, null=True)),
                ('updateuser', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TB_MEMBER',
                'managed': True,
            },
        ),
    ]
