# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbAdminaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('accountid', models.CharField(db_column='accountId', max_length=24)),
                ('accountpw', models.CharField(db_column='accountPw', max_length=70)),
                ('accountnm', models.CharField(db_column='accountNm', max_length=10)),
                ('accountph', models.CharField(blank=True, db_column='accountPh', max_length=15, null=True)),
                ('accountdpt', models.CharField(blank=True, db_column='accountDpt', max_length=60, null=True)),
                ('accountemail', models.CharField(blank=True, db_column='accountEmail', max_length=60, null=True)),
                ('accountlv', models.CharField(db_column='accountLv', max_length=2)),
                ('state', models.CharField(blank=True, max_length=1, null=True)),
                ('insertuser', models.CharField(blank=True, db_column='insertUser', max_length=24, null=True)),
                ('updateuser', models.CharField(blank=True, db_column='updateUser', max_length=24, null=True)),
                ('updatedate', models.CharField(blank=True, db_column='updateDate', max_length=21, null=True)),
                ('insertdate', models.CharField(db_column='insertDate', max_length=21)),
            ],
            options={
                'db_table': 'TB_ADMINACCOUNT',
                'managed': False,
            },
        ),
    ]
