# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_tbadminaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbmember',
            options={'managed': False, 'ordering': ['-updatedate']},
        ),
    ]
